# Generated by Django 4.0.4 on 2022-12-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=500)),
                ('is_published', models.BooleanField(blank=True)),
                ('image', models.ImageField(default='...', upload_to='')),
                ('author_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
