# Generated by Django 4.0.4 on 2022-11-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
