# Generated by Django 4.1.4 on 2022-12-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0003_adscompilation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscompilation',
            name='owner',
        ),
        migrations.AddField(
            model_name='adscompilation',
            name='owner_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
