# Generated by Django 4.1.4 on 2022-12-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_adscompilation_owner_adscompilation_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
