# Generated by Django 4.1.4 on 2022-12-29 12:47

import category.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True, validators=[category.validators.check_length_of_slug]),
        ),
    ]
